---
title: "8 best months of NASDAQ"
author: "D A Trading"
date: "5/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(quantmod)

getSymbols("^IXIC",
           from = "1971-01-01",
           to = "2019-12-31",
           src = "yahoo")

head(IXIC, 20)
```

```{r}
# Creating a data frame with closing prices and date
library(dplyr)
library(lubridate)
library(tibble)

NSDQ <- rownames_to_column(as.data.frame(IXIC), var = "date") %>% 
  mutate(date = ymd(date)) %>% 
  select(date, IXIC.Close, IXIC.Volume) %>% 
  rename(Close = IXIC.Close,
         Volume = IXIC.Volume)

NSDQ
```

```{r}
# Creating a data frame consisting weeks and their closing prices
NSDQmth <- NSDQ %>% 
  mutate(month = as.integer(month(date)),
         year = year(date)) %>% 
  group_by(year, month) %>% 
  filter(date == max(date)) 

# Using "lag" to create weekly percentage closing prices
NSDQmth$lag <- lag(NSDQmth$Close)

NSDQmth <- NSDQmth %>% 
  mutate(perc_close = (Close - lag)/Close * 100) %>% 
  na.omit() %>% 
  select(-lag)

NSDQmth
```

```{r}
# Creating a new column called "decade"
decade <- function(x){
  if(x < 1980){
    x <- "1970-1979"
  } else if(x < 1990){
    x <- "1980-1989"
  } else if(x < 2000){
    x <- "1990-1999"
  } else if(x < 2010){
    x <- "2000-2009"
  } else if(x < 2020){
    x <- "2010-2019"
  }
  return(x)
}

NSDQmth$decade <- as.factor(sapply(NSDQmth$year, decade))

decadecode <- function(x){
  if(x < 1980){
    x <- 1
  } else if(x < 1990){
    x <- 2
  } else if(x < 2000){
    x <- 3
  } else if(x < 2010){
    x <- 4
  } else if(x < 2020){
    x <- 5
  }
  return(x)
}

NSDQmth$decade_code <- as.factor(sapply(NSDQmth$year, decadecode))

NSDQmth
```

```{r}
# Creating a new object that has the %changes compared to previous November
# Step1: Create a dataframe with only closing price of each November
octclose <- NSDQmth %>% 
  filter(month == 10) %>% 
  select(Close, year) %>% 
  rename(octclose = Close)

# Create a new column for studyyear which starts in November
octclose$studyyear <- seq(1,49,1)

# Step2: Calculating %change for each month since previous November
# Note: All months in 1971 before November are discarded as no prior November to reference from
delta1 <- NSDQmth[, c(2,4,5,7)] %>% 
  filter(month %in% c(1:6,10:12)) 

# Creating a similar column of studyyear
deltayear <- delta1[-c(1:4,437:439),]
deltayear$studyyear <- rep(1:48, each = 9)
deltayear$studymth <- rep(seq(0,8,1),48)

NSDQ8best <- deltayear %>%  
  inner_join(octclose, by = "studyyear") %>% 
  mutate(delta_perc = (Close - octclose)/Close * 100) %>% 
  select(c(2:6, 10)) %>% 
  rename(month = month.x,
         year = year.x) %>% 
  ungroup() %>% 
  mutate_at(c("month", "year", "studyyear", "studymth"), as.factor)

NSDQ8best
```

```{r}
# Heatmap
library(ggplot2)

NSDQ8best %>% 
  filter(studymth != 0) %>% 
  ggplot(aes(x = studymth, y = year, fill = delta_perc))+
  geom_tile()+
  scale_fill_gradient2(low = "red", high = "green4", mid = "white", midpoint = 0)+
  theme_minimal()+
  scale_x_discrete(labels = c("Nov","Dec","Jan","Feb","Mar","Apr","May","Jun"))+
  scale_y_discrete(breaks = c(seq(1971, 2019, 3)))+
  labs(x = "Month",
       title = "Heatmap of Nasdaq changes compared to end of Oct",
       caption = "Red signifies percentage change for that week lower than end of May",
       fill = "% change")
```


```{r}
# Faceted Heat Map

NSDQ8best %>% 
  filter(studymth != 0) %>% 
  ggplot(aes(x = studymth, y = year, fill = delta_perc))+
  geom_tile()+
  scale_fill_gradient2(low = "red", high = "green4", mid = "white", midpoint = 0)+
  theme_minimal()+
  scale_x_discrete(labels = c("Nov","Dec","Jan","Feb","Mar","Apr","May","Jun"))+
  theme(axis.text.y = element_blank())+
  labs(x = "Month",
       y = "Year",
       title = "Heatmap of Nasdaq changes compared to end of Oct",
       caption = "Red signifies percentage change for that week lower than end of May",
       fill = "% change")+
  facet_wrap(~ decade, ncol = 1, scale = "free_y")
```

```{r}
# Line plot
library(plotly)

ggplotly(
NSDQ8best %>% 
  ggplot(aes(x = as.integer(studymth), y = delta_perc))+
  geom_line(aes(color = year), show.legend = F)+
  geom_hline(yintercept = 0)+
  theme_minimal()+
  labs(x = "Month starting from End Oct",
       y = "% change from End of Oct",
       title = "%change from End of Oct to Jun by Year")
)
```

```{r}
# Box plot

NSDQ8best %>% 
  filter(studymth != 0) %>% 
  ggplot(aes(x = studymth, y = delta_perc))+
  geom_boxplot(color = "blue")+
  geom_hline(yintercept = 0)+
  theme_minimal()+
  scale_x_discrete(labels = c("Nov","Dec","Jan","Feb","Mar","Apr","May","Jun"))+
  labs(x = "Month starting from Nov",
       y = "% change from End of Nov",
       title = "%change from End of Nov to May by Year")
```

```{r}
# Study by looking at full year

NSDQmth %>% 
  ggplot(aes(x = as.factor(month), y = perc_close))+
  annotate(xmin = 5.5, xmax = 10.5, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2)+
  geom_boxplot(color = "blue")+
  geom_hline(yintercept = 0)+
  theme_minimal()+
  scale_x_discrete(labels = c("Jan","Feb","Mar","Apr","May","Jun", "Jul", "Aug", "Sep", "Oct", "Nov","Dec"))+
  labs(x = "Month",
       y = "% change from End of Nov",
       title = "%change of every month")
```

```{r}
# Aggregate %change by month
NSDQmthagg <- NSDQmth %>% 
  mutate(up = perc_close > 0,
         down = perc_close < 0) %>% 
  group_by(month) %>% 
  summarize(mean = mean(perc_close),
            median = median(perc_close),
            up_occur = sum(up),
            down_occur = sum(down)) %>% 
  mutate(mean_up = mean > 0,
         median_up = median > 0)
```

```{r}
# Column plot MEAN

NSDQmthagg %>% 
  ggplot(aes(x = month, y = mean, fill = mean_up)) + 
  annotate(xmin = 6.5, xmax = 10.5, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2)+
  geom_col()+
  theme_minimal()+
  scale_x_continuous(breaks = c(1:12))+
  scale_fill_manual(values = c("red", "green4"))+
  labs(y = "Mean % change",
       title = "MEAN % change for each month 1971 - 2019",
       fill = "% change")
```

```{r}
# Column plot MEDIAN

NSDQmthagg %>% 
  ggplot(aes(x = month, y = median, fill = median_up)) + 
  annotate(xmin = 6.5, xmax = 10.5, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2)+
  geom_col()+
  theme_minimal()+
  scale_fill_manual(values = c("green4", "red"))+
  scale_x_continuous(breaks = c(1:12))+
  labs(y = "Median % change",
       title = "MEDIAN % change for each month 1971 - 2019",
       fill = "% change")
```

```{r}
# Column plot proportion

library(tidyr)
NSDQmthagg %>% 
  select(month, up_occur, down_occur) %>% 
  gather(-month, key = "up_down", value = "occur") %>% 
  ggplot(aes(x = month, y = occur, fill = up_down))+
  geom_col(position = "fill")+
  annotate(xmin = 6.5, xmax = 10.5, ymin = -Inf, ymax = Inf, geom = 'rect', alpha = 0.2, color = "black")+
  geom_hline(yintercept = 0.5)+
  theme_minimal()+
  scale_fill_manual(values = c("red", "green4"))+
  scale_x_continuous(breaks = c(1:12))+
  labs(y = "Ratio of Up vs Down weeks",
       title = "Proportion of Up vs Down weeks 1971 - 2019",
       fill = "")
```

```{r}
# t-test for statistical difference for all years

JultoOct <- NSDQmth %>% 
  filter(month %in% c(7:10)) 

NovtoJun <- NSDQmth %>% 
  filter(month %in% c(1:6, 11, 12))

testall <- t.test(NovtoJun$perc_close, JultoOct$perc_close, alternative = "less")

testall
```

```{r}
# Testing for loop for t-test

pval <- vector("numeric", 5L)

for(i in 1:5){
  w <- NSDQmth %>% 
  filter(month %in% c(7:10),
         decade_code == i)
  
  x <- NSDQmth %>% 
  filter(month %in% c(1:6, 11, 12),
         decade_code == i)
  
  y <- t.test(x$perc_close, w$perc_close, alternative = "less")
  
  pval[i] <- y$p.value
}

pval <- pval %>% 
  append(testall$p.value)

labels <- append(as.vector(unique(NSDQmth$decade)), "All")

data.frame("decade" = labels, pvalues)
```

# Profitability comparisons 
# 1. Compare B&H vs sell June buy November(by decade)
# 2. Compare Sell June buy Nov of NSDQ vs Sell another month buy 5 months later

```{r}
# Creating for loop for portfolio gains via buy and hold, by decade

bnh <- vector("numeric", 5L)

for(i in 1:5){
a <- NSDQmth %>% 
  filter(decade_code == i)
bnh[i] <- a$Close[nrow(a)] - a$Close[1]
}

bnh
```


```{r}
# Creating for loop for portfolio gains in the July to Oct window, by decade

Julwindow <- vector("numeric", 5L)

for(i in 1:5){
c <- NSDQmth %>% 
  filter(decade_code == i,
         month %in% c(6,10)) 

c$lag <- lag(c$Close)

d <- c %>% 
  mutate(gain = Close - lag) %>% 
  filter(month == 10) %>% 
  ungroup() %>% 
  summarize(gain = sum(gain))
Julwindow[i] <- d$gain
}

Julwindow

```

```{r}
# Compiling Buy and Hold results

decade <- c("1970-1979", "1980-1989", "1990-1999", "2000-2009", "2010-2019")
decade_code <- c(1:5)

portfoliodf <- data.frame(decade, decade_code, "buy_n_hold" = bnh, "gain_jul_to_oct" = Julwindow) %>% 
  mutate(nov_to_jun = buy_n_hold - gain_jul_to_oct,
         savings = -gain_jul_to_oct,
         perc_of_bnh = nov_to_jun/buy_n_hold*100)

portfoliodf
```

```{r}
# Total BnH vs NovtoJun for all 49 years
bnh49 <- portfoliodf %>% 
  summarize(BnH = sum(buy_n_hold),
          nov_to_jun = sum(nov_to_jun)) %>% 
  mutate(savings = nov_to_jun - BnH)

bnh49
```

```{r}
# Visualize portfolio differences by decade
library(ggplot2)

portfoliogg <- portfoliodf[,c(1,2,3,5)] %>%
  gather(-decade, -decade_code, key = "strategy", value = "gains")

for(i in 1:5){
e <- portfoliogg %>% 
  filter(decade_code == i) %>% 
  ggplot(aes(x = decade, y = gains, fill = as.factor(strategy)))+
  geom_col(position = "dodge")+
  theme_minimal()+
  geom_hline(yintercept = 0)+
  labs(x = "Decade", y = "Portfolio Gains", title = "Portfolio Gains by Decade", fill = "Strategy")
  print(e)
}

# Visualize portfolio difference over 49 years
bnh49[,-3] %>% 
  gather(key = "Strategy", value = "Gain") %>% 
  ggplot(aes(x = Strategy, y = Gain, fill = Strategy))+
  geom_col()+
  theme_minimal()+
  geom_hline(yintercept = 0)+
  labs(title = "Portfolio Gains from 1979 to 2019", fill = "Strategy")
```

```{r}
# Using for loop to create other 4-month windows

# Define my end object as vector
exe1 <- vector("numeric", 8L)

for(i in 1:8){ # Only from Jan to August bcos Sep onwards would go to month "13".
  j <- i + 4 # The 4 month window
  m <- NSDQmth %>% 
  filter(month %in% c(i,j)) 
  m$lag <- lag(m$Close)
  n <- m %>% 
  mutate(gain = Close - lag) %>% 
  filter(month == j) %>% 
  na.omit() %>% # There will be NA for windows starting Jan and Feb bcos data started in March 1971
  ungroup() %>% 
  summarize(gain = sum(gain))
  exe1[i] <- n$gain # Returning a VECTOR. Else "n" is a dataframe.
}
  
for(i in 1:4){ # For the months Sep to Dec
  j <- i + 8
  m <- NSDQmth %>% 
  filter(month %in% c(i,j)) 
  m$lag <- lag(m$Close)
  n <- m %>% 
  mutate(gain = Close - lag) %>% 
  filter(month == i) %>% # Unlike earlier code, we choose for i, not j.
  na.omit() %>% 
  ungroup() %>% 
  summarize(gain = sum(gain))
  exe1[j] <- n$gain # Adding on our results to the same object from row 9 onwards.
}

exe1

portfoliomth <- data.frame("start_month" = c(1:12), "buy_n_hold" = bnh49$BnH, "window_gains" = exe1) %>% 
  mutate(gains = buy_n_hold - window_gains) %>% 
  select(1,4)

portfoliomth %>% 
  rbind(data.frame("start_month" = "All", gains = bnh49$BnH)) %>% 
  ggplot(aes(x = as.factor(start_month), y = gains, fill = gains))+
  geom_col()+
  theme_minimal()+
  scale_fill_gradient(low = "grey", high = "green4")+
  geom_hline(aes(yintercept = gains[6]), linetype = "dashed")+
  labs(x = "Four month exclusion window beginning end of month",
       y = "Cumulative Portfolio gains",
       title = "Portfolio Gains if 4-month window excluded beginning end of month X", 
       caption = "Cumulative portfolio from 1979 to 2019")
```

